# -*- coding: utf-8 -*-
"""DS_PROJETOS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e0XUFq8zqkP5IprNKK3cwKZyTRZ34wBv

# VALOR APOS SAQUE
"""

saldo_total = int(input())
valor_saque = int(input())

if valor_saque <= saldo_total:
  saldo = saldo_total - valor_saque
  print(f'Saque realizado com sucesso. Novo saldo: {saldo}')

else:
  print('Saldo insuficiente. Saque nao realizado!')

"""# JUROS COMPOSTOS INVESTIMENTO"""

valor_inicial = float(input())
taxa_juros = float(input())
periodo = int(input())

valor_final = valor_inicial * (taxa_juros + 1 )**periodo

valor_final = round(valor_final, 2)
print(f"Valor final do investimento: R$ {valor_final}")

"""# SALDO EM CONTA CORRENTE APOS DEPOSITO, VERIFICAÇAO DE VALOR VALIDO"""

valor = float(input())

saldo_atual = 0
if valor > 0:
  saldo_atual = saldo_atual + valor
  print(f'Deposito realizado com sucesso! saldo atual R$ {saldo_atual}')
elif valor == 0:
   print('Encerrando o programa...')
else:
  print('Valor invalido! Digite um valor maior que zero.')

    """# ATIVOS """
ativos = []

# Entrada da quantidade de ativos
quantidadeAtivos = int(input())

# Entrada dos códigos dos ativos
for _ in range(quantidadeAtivos):
    codigoAtivo = input()
    ativos.append(codigoAtivo)

ativos.sort()

for palavra in ativos:
  print(palavra)
